config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: 'pages#profile'

  resources :beaches, only: [:index, :show]

  resources :packs, only: [] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beach.rb
class Beach < ApplicationRecord
  has_many :packs
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pack
  belongs_to :user

  has_one :beach, through: :pack

  validates :date, presence: true
end

app/models/pack.rb
class Pack < ApplicationRecord
  belongs_to :beach
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,
            presence: true,
            length: { minimum: 3 },
            format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/beaches_controller.rb
class BeachesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @beaches = Beach.all

    if params[:query].present?
      sql_subquery = "name ILIKE :query OR location ILIKE :query OR continent ILIKE :query"
      @beaches = @beaches.where(sql_subquery, query: "%#{params[:query]}%")
    end

    @markers = @beaches.geocoded.map do |beach|
      {
        lat: beach.latitude,
        lng: beach.longitude
      }
    end
  end

  def show
    @beach = Beach.find(params[:id])
    @booking = Booking.new

    @markers = [{
      lat: @beach.latitude,
      lng: @beach.longitude
    }]
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.pack = Pack.find(params[:pack_id])
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path, notice: "Booking was successfully created."
    else
      @beach = @booking.beach
      render "beaches/show", status: :unprocessable_entity
    end
  end

  def index
    @bookings = Booking.where(user:current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @beaches = [Beach.first, Beach.second, Beach.third, Beach.fourth]
  end

  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beaches/_description.html.erb
<h4 class="mb-4">Beach Description</h4>
<p class="h5">
  <%= @beach.description %>
</p>

app/views/beaches/_filter_by_continent.html.erb
<div class="filter p-3">
  <div class="globe-icons text-center">
    <%= link_to beaches_path(query: "africa") do %>
      <i class="fa-solid fa-earth-africa"></i>
      <p>Africa</p>
    <% end %>
    <%= link_to beaches_path(query: "america") do %>
      <i class="fa-solid fa-earth-americas"></i>
      <p>America</p>
    <% end %>
    <%= link_to beaches_path(query: "asia") do %>
      <i class="fa-solid fa-earth-asia"></i>
      <p>Asia</p>
    <% end %>
    <%= link_to beaches_path(query: "europe") do %>
      <i class="fa-solid fa-earth-europe"></i>
      <p>Europe</p>
    <% end %>
    <%= link_to beaches_path(query: "oceania") do %>
      <i class="fa-solid fa-earth-oceania"></i>
      <p>Oceania</p>
    <% end %>
  </div>
</div>

app/views/beaches/_index_map.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/beaches/_packs-card.html.erb
<div class = "mt-5 mb-5 border shadow rounded-4 bg-white p-3">
  <ul class="nav nav-tabs packs-card" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link border-top-0 border-end-0 border-start-0 active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Basic</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link border-top-0 border-end-0 border-start-0" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Standard</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link border-top-0 border-end-0 border-start-0" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Premium</button>
    </li>
  </ul>
  <div class="tab-content packs-card" id="myTabContent">

    <div class="tab-pane fade show active p-3" id="home" role="tabpanel" aria-labelledby="home-tab" data-controller = "confirm-booking">
      <h3 class = "text-center"><strong><%= @beach.packs[0].price %></strong>€ day</h3>
      <h5>Description</h4>
      <ul>
       <% @beach.packs[0].description.split("-").each do |bullet| %>
        <li><%= bullet %></li>
        <% end %>
      </ul>

      <%= simple_form_for [@beach.packs[0],@booking] do |f| %>
       <%= f.input :date, as: :string, label: "When do you want to go?", input_html: { data: { controller: "datepicker", confirm_booking_target: "date" }, placeholder: "Select a date" } %>
        <button type="button" class="button-packs" data-bs-toggle="modal" data-bs-target="#exampleModal" data-action="click->confirm-booking#getDate" >
          Book Now
        </button>

       <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content border shadow rounded-4">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Your Booking Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p><strong>Beach:</strong> <%= @beach.name %></p>
                <p><strong>Pack:</strong> <%= @beach.packs[0].name %></p>
                <p><strong>Date:</strong> <span data-confirm-booking-target = "modalDate"></span></p>
                <p><strong>Price:</strong> <%= @beach.packs[0].price %>€</p>
              </div>
              <div class="modal-footer justify-content-center">
                <button type="button" class="modal-cancel-btn" data-bs-dismiss="modal">Cancel Booking</button>
                 <%= f.submit "Confirm Booking", class: "modal-confirm-btn" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="tab-pane fade p-3" id="profile" role="tabpanel" aria-labelledby="profile-tab" data-controller = "confirm-booking">
      <h3 class = "text-center"><strong><%= @beach.packs[1].price %></strong>€ day</h3>
      <h5>Description</h4>
      <ul>
       <% @beach.packs[1].description.split("-").each do |bullet| %>
        <li><%= bullet %></li>
        <% end %>
      </ul>

      <%= simple_form_for [@beach.packs[1],@booking] do |f| %>
       <%= f.input :date, as: :string, label: "When do you want to go?", input_html: { data: { controller: "datepicker", confirm_booking_target: "date" }, placeholder: "Select a date" } %>
        <button type="button" class="button-packs" data-bs-toggle="modal" data-bs-target="#exampleModal2" data-action="click->confirm-booking#getDate" >
          Book Now
        </button>

       <!-- Modal -->
        <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content border shadow rounded-4">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel2">Your Booking Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p><strong>Beach:</strong> <%= @beach.name %></p>
                <p><strong>Pack:</strong> <%= @beach.packs[1].name %></p>
                <p><strong>Date:</strong> <span data-confirm-booking-target = "modalDate"></span></p>
                <p><strong>Price:</strong> <%= @beach.packs[1].price %>€</p>
              </div>
              <div class="modal-footer justify-content-center">
                <button type="button" class="modal-cancel-btn" data-bs-dismiss="modal">Cancel Booking</button>
                 <%= f.submit "Confirm Booking", class: "modal-confirm-btn" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="tab-pane fade p-3" id="contact" role="tabpanel" aria-labelledby="contact-tab" data-controller = "confirm-booking">
      <h3 class = "text-center"><strong><%= @beach.packs[2].price %></strong>€ day</h3>
      <h5>Description</h4>
      <ul>
       <% @beach.packs[2].description.split("-").each do |bullet| %>
        <li><%= bullet %></li>
        <% end %>
      </ul>

      <%= simple_form_for [@beach.packs[2],@booking] do |f| %>
       <%= f.input :date, as: :string, label: "When do you want to go?", input_html: { data: { controller: "datepicker", confirm_booking_target: "date" }, placeholder: "Select a date" } %>
        <button type="button" class="button-packs" data-bs-toggle="modal" data-bs-target="#exampleModal3" data-action="click->confirm-booking#getDate" >
          Book Now
        </button>

       <!-- Modal -->
        <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel3" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content border shadow rounded-4">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel3">Your Booking Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p><strong>Beach:</strong> <%= @beach.name %></p>
                <p><strong>Pack:</strong> <%= @beach.packs[2].name %></p>
                <p><strong>Date:</strong> <span data-confirm-booking-target = "modalDate"></span></p>
                <p><strong>Price:</strong> <%= @beach.packs[2].price %>€</p>
              </div>
              <div class="modal-footer justify-content-center">
                <button type="button" class="modal-cancel-btn" data-bs-dismiss="modal">Cancel Booking</button>
                 <%= f.submit "Confirm Booking", class: "modal-confirm-btn" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/beaches/_show-map.html.erb
<div class="container">
  <h3>Where you’ll be</h3>
  <p><%= @beach.location %></p>
    <div class="mb-5" style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/beaches/_show_banner.html.erb
<div class="d-flex justify-content-between mt-5 mb-3">
  <div class = "d-inline-block" >
    <h3 class= "beach-name"><%= @beach.name.upcase %></h3>
    <h4><%= @beach.location.capitalize %></h4>
  </div>

  <div>
    <i class="fa-regular fa-heart" style="color:red"></i>
    <%= link_to "Save", beaches_path, style:"color:black" %>
  </div>
</div>
<div class="image-beach rounded-4" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= image_path @beach.image_url %>')">
</div>

app/views/beaches/index.html.erb
<div class="container">
  <%= render "filter_by_continent" %>

  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
      <% @beaches.each do |beach| %>
        <div class="col d-flex justify-content-center">
          <%= link_to beach_path(beach.id) do %>
            <%= render "shared/card", beach: beach %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="p-3 maps">
    <h2>Beaches location</h2>
    <%= render "index_map" %>
  </div>

</div>

app/views/beaches/show.html.erb
<div class="container">
  <%= render "beaches/show_banner" %>
  <div class="container">
    <div class="row">
      <div class="col-7 mt-5"><%= render "beaches/description" %></div>
      <div class="col-5"><%= render "beaches/packs-card" %></div>
    </div>
  </div>
  <%= render "beaches/show-map" %>
</div>

app/views/bookings/_card_bookings.html.erb
<div class="">
  <div class="d-flex flex-row gap-3 mb-3 pb-2 align-items-center">
    <%= image_tag booking.beach.image_url, class: "rounded-4", width: 120, height: 120  %>
    <div>
      <h5><%= booking.beach.name %></h5>
      <p class="description-text"><%= booking.date %></p>
      <p class="description-text"><%= booking.pack.name %></p>
      <p class="description-text"><%= booking.status.capitalize %></p>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container" style="margin-bottom: 80px;">
  <div class="row d-flex flex-row mt-5 mb-5">
    <div class="col">
      <h3 class="mb-4">My Bookings</h3>
      <div class="justify-content-between mb-3">
        <% @bookings.each do |booking| %>
          <%= render "card_bookings", booking: booking %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandspot</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>


  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="banner d-flex flex-column" style="background-image: url(https://images.pexels.com/photos/130879/pexels-photo-130879.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
        <h1 class="title">Dunes & Dreams: Crafting <br> Memories by the Seashore</h1>
        <%= link_to "Book Now", beaches_path, class: "button" %>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner d-flex flex-column" style="background-image: url(https://i.insider.com/56981adbc08a8034008b9bf5?width=1136&format=jpeg);">
        <h1 class="title">Serene Sands <br> Your Personal Oasis </h1>
        <%= link_to "Book Now", beaches_path, class: "button" %>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner d-flex flex-column" style="background-image: url(https://www.beaches.com/blog/content/images/2019/11/Beaches-Negril-Jamaica-Seven-Mile-Beach-Family2.jpg);">
        <h1 class="title">Lifetime of Laughter <br> Every Footprint tells a Family Tale </h1>
        <%= link_to "Book Now", beaches_path, class: "button" %>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner d-flex flex-column" style="background-image: url(https://www.viajali.com.br/wp-content/uploads/2018/09/praias-em-portugal-0.jpg);">
        <h1 class="title">  Panoramic Paradise <br> You can Own the View </h1>
        <%= link_to "Book Now", beaches_path, class: "button" %>
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner d-flex flex-column" style="background-image: url(https://vidacigana.com/wp-content/uploads/2021/03/melhores-praias-lisboa-23.jpg);">
        <h1 class="title"> Nature's Finest <br> More Than Just Sand </h1>
        <%= link_to "Book Now", beaches_path, class: "button" %>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/home.html.erb
<%= render "banner" %>
<div class="container pt-4">
  <h2>Most popular</h2>
  <div class="d-flex flex-direction-row gap-5 mt-3 mb-5">
    <% @beaches.each do |beach| %>
      <%= link_to beach_path(beach.id) do %>
        <%= render "shared/card", beach: beach %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="row d-flex flex-row mt-5 mb-5">
    <div class="col">
      <h3 class="mb-4">My Profile</h3>
      <img class="user-photo" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg?w=2000" />
      <div class="d-flex flex-row justify-content-between border-bottom mb-3">
        <div>
          <p>Full Name</p>
          <p class="text-secondary"><%= @user.name.capitalize %></p>
        </div>
        <div>
          <a href="#" class="text-secondary">Edit</a>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-between border-bottom mb-3">
        <div>
          <p>Email</p>
          <p class="text-secondary"><%= @user.email %></p>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-between border-bottom mb-3">
        <div>
          <p>Password</p>
          <p class="text-secondary">*********</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card border-0 card-beach" style="width: 17rem;">
  <%= image_tag beach.image_url, alt: "beach image", class: "card-image" %>
  <div class="card-body ps-0 ">
    <h4 class="card-title"><%= beach.name %></h4>
    <h5 class="card-text m-0"><%= beach.location %></h5>
    <p class="card-text">From 50€ <span style="font-size: 10px">/day</span></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
  
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container d-flex flex-row justify-content-between">
    <div>
      <ul>
      <i class="fa-regular fa-copyright fa-2xs"></i>
        <li>2023 <span>SandSpot</span> Inc. All rights reserved</li>
        <i class="fa-solid fa-circle"></i>
        <li><%= link_to "Terms", beaches_path %></li>
        <i class="fa-solid fa-circle"></i>
        <li><%= link_to "Sitemap", beaches_path %></li>
        <i class="fa-solid fa-circle"></i>
        <li><%= link_to "Privacy", beaches_path %></li>
      </ul>
    </div>
    <div class="social-links">
      <a href="https://www.facebook.com/" class="social-link"><i class="fa-brands fa-facebook"></i></a>
      <a href="https://www.instagram.com/" class="social-link"><i class="fa-brands fa-instagram"></i></a>
      <a href="https://www.linkedin.com/" class="social-link"><i class="fa-brands fa-linkedin"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-sandspot sticky-top">
  <div class="container-fluid custom-container">
    <a class="navbar-brand" href="/"><i class="fa-solid fa-umbrella-beach "></i> SandSpot</a>

    <%= form_with url: beaches_path, method: :get, class: "simple_form search" do %>
      <div class="search-form-control form-group">
        <%= text_field_tag :query,
              params[:query],
              class: "form-control string required",
              placeholder: "Where do you want to go?"
        %>
        <%= button_tag type: 'submit', name: '', class: 'btn btn-flat' do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    <% end %>

    <div class="d-flex">
      <% if current_user.present? %>
        <p class="m-2 me-3">Welcome, <%= current_user.name.capitalize %></p>
      <% end %>
      <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg?w=2000" />
    </div>
    <div class="dropdown-menu dropdown-menu-end dropdown" aria-labelledby="navbarDropdown">
      <%= link_to "Login", user_session_path, class: "dropdown-item" %>
      <%= link_to "Signup", new_user_session_path, class: "dropdown-item" %>
      <%= link_to "My profile", profile_path, class: "dropdown-item" %>
      <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
      <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</div>